### ISSUE TITLE
Add option to upload recording route

### ISSUE THREAD

**Issue by robachmann** [BradPatras/gpx-recorder#41]
Hi @BradPatras 

Thank you so much for this fantastic app. I really like the uncluttered design and your focus on key features. Google's Play store is full of route recorders but none can compete with this in terms of code transparency, data economy and reliability.

Seeing that 24 others have starred this repo make me believe that there is a small community that loves being in control of their own data and are glad this app exists. 

I love using this app to record hiking activities. It's great to see a route when it's finished and I enjoy archiving my past hikes. At the same time, others might be interested to know where I currently am. I've written a small backend service that can process gpx files which allows me to store a recorded route. It would be really great if this app would offer an option to continuously upload live routes to a given backend.

I could imaging these config options:
1. Backend URL
2. HTTP method (POST/PUT)
3. Auth (basic/none)
4. Upload interval: Either x minutes or a given multiple of the recording interval (interval=90s & config=5 -> upload every 7m30s)

If an upload fails, the records should be kept locally and 0 to 2 retries attempted before the task is skipped and retried at the next interval. I'm undecided if always the complete route should be uploaded or only segments that haven't been replicated yet. 

Thank you very much for considering this input and best,
Roman

**Comment by BradPatras** [comment]
Thanks for this post! I'm definitely interested in supporting this use case...

I think providing full custom upload support might be a bit much for a feature that may only be used for power users (like yourself).

I'm still open to the idea but what would you think about this: Instead of adding "Automatic Upload" we could add an "Automatic Export" that will export the route file to a location on your device automatically as you're recording. 
Then you could use a third party solution that will automatically upload the file from that location every so often.  I think the automatic export feature would be a more common use-case for the average user while still enabling your more advanced use-case (with some extra leg-work required)

Let me know what you think!

**Comment by BradPatras** [comment]
Closing this for now

**Comment by jimkleine** [comment]
@BradPatras I'm interested in contributing this feature, starting with an MVP for my specific use case (tracking pamphlet deliveries for NZ's upcoming general election).

For now, I just want to add an option to upload a track to an OpenStreetMap service as each recording ends, but I'm happy to keep it flexible to be able to support timed uploads later.

Are you:

1.  Currently accepting pull requests for this project; and
2.  Potentially available to answer occasional questions about design choices and the existing code base if I need help?

**Comment by BradPatras** [comment]
@jimkleine I think the feature as you describe it is more feasible than the original ask of this issue. I'd definitely support adding an "auto upload on-recording end" feature as long as we can figure out how to make it user-friendly and not too narrowly focused around your specific use-case.

I am open to pull requests and you can reach out to me for any assistance in getting the app building locally. Lets move this conversation into this discussion I just created: #59
